---
name: Wordpress
description: >
  O sistema de gerenciamento de conte√∫do rico do WordPress pode utilizar plugins, widgets e temas.
version: 0.0.1-wordpress-rancher
category: CMS
maintainer: Marcelo Bomfim
license: GNU GPL v3
projectURL: https://github.com/marcelobomfim/catalogs-rancher
